version: "3.9"
services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    depends_on:
      - db
    container_name: api
    env_file:
      - ./api/.env
    restart: on-failure
    volumes:
      - ./api:/api

  web:
    build: ./web
    ports:
      - "3000:3000"
    container_name: web
    env_file:
      - ./web/.env
    stdin_open: true
    restart: on-failure
    volumes:
      - ./web:/web
      - node_modules:/web/node_modules

  db:
    image: postgres:15.1-alpine
    container_name: db
    restart: on-failure
    env_file:
      - ./api/.env
    ports:
      - '5432:5432'
    volumes:
      - psql_data:/var/lib/postgresql/data

volumes:
  psql_data:
  node_modules:
