version: "3.9"
services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    depends_on:
      - db
    container_name: api
    env_file:
      - ./api/.env
    restart: on-failure
    volumes:
      - ./api:/api

  client:
    build: ./client
    ports:
      - "3000:3000"
    container_name: client
    env_file:
      - ./client/.env
    restart: on-failure
    volumes:
      - ./client:/client
      - node_modules:/client/node_modules

  db:
    image: postgres:15.1-alpine
    container_name: db
    restart: on-failure
    env_file:
      - ./api/.env
    ports:
      - "5432:5432"
    volumes:
      - psql_data:/var/lib/postgresql/data

  webserver:
    build: ./webserver
    ports:
      - "80:80"
      - "443:443"
    container_name: nginx
    restart: on-failure
    depends_on:
      - client
      - api

volumes:
  psql_data:
  node_modules:
