# syntax=docker/dockerfile:1.2

FROM public.ecr.aws/lambda/python:3.11-preview.2023.05.13.01

RUN pip install poetry --root-user-action=ignore

COPY poetry.lock pyproject.toml ./
RUN poetry config virtualenvs.create false && poetry install --no-interaction --no-ansi --no-root

COPY . .

CMD ["core.main.handler"]